### PR TITLE
Update deps and fix of source compatibility issues

### PR DESCRIPTION
**Pull request by fogfish**
```
./
v1.16.11     ⇒ v1.30.3     	github.com/aws/aws-sdk-go-v2
v1.17.1      ⇒ v1.27.27    	github.com/aws/aws-sdk-go-v2/config
v1.54.0      ⇒ v1.173.0    	github.com/aws/aws-sdk-go-v2/service/ec2
v1.14.14     ⇒ v1.27.5     	github.com/aws/aws-sdk-go-v2/service/pi
v1.24.0      ⇒ v1.82.0     	github.com/aws/aws-sdk-go-v2/service/rds
v0.6.6       ⇒ v0.7.1      	github.com/montanaflynn/stats
v3.13.1      ⇒ v3.14.6     	github.com/schollz/progressbar/v3
v1.2.1       ⇒ v1.8.1      	github.com/spf13/cobra
v0.2.0       ⇒ v0.4.0      	go.uber.org/mock
```

### CODE REVIEW

**Comment by fogfish** [comment]
👍

**Comment by szuecs** [comment]
:+1:

**Comment by larry-dalmeida** [comment]
👍

**Review by larry-dalmeida — APPROVED** [review]

**Comment by fogfish** [comment]
👍

**Comment by fogfish** [comment]
```
./
v1.30.3      ⇒ v1.30.5     	github.com/aws/aws-sdk-go-v2
v1.27.27     ⇒ v1.27.33    	github.com/aws/aws-sdk-go-v2/config
v1.173.0     ⇒ v1.177.3    	github.com/aws/aws-sdk-go-v2/service/ec2
v1.27.5      ⇒ v1.27.9     	github.com/aws/aws-sdk-go-v2/service/pi
v1.82.0      ⇒ v1.82.5     	github.com/aws/aws-sdk-go-v2/service/rds
v3.14.6      ⇒ v3.15.0     	github.com/schollz/progressbar/v3
```

**Comment by fogfish** [comment]
👍

**Comment by fogfish** [comment]
@larry-dalmeida Please review it again with thumb up! Apparently, PR has to be touched before zappr accepts changes.

**Comment by fogfish** [comment]
👍

**Comment by fogfish** [comment]
@pioneerit @tcondeixa @remychantenay Could you please check this one?

**Comment by tcondeixa** [comment]
👍

**Comment by fogfish** [comment]
Thank you @tcondeixa !

**Pull request merged**
